### ISSUE TITLE
[Feature 1] User Profiles

### ISSUE THREAD

**Issue by hongzipkim** [CSC207-2022F-UofT/course-project-group-82#7]
A page with recommendations (a post) made by the users, along with basic social media information (e.g. follower, following)

**Comment by hongzipkim** [comment]
**Properties:** FlaggedRestaurants, a list of Restaurant objects 
Includes the user’s username, name, and profile picture. It will also include their followers, followings, and the number of check-ins they have made.
Within the main class, we will also have a **Post** subclass, where we have a list of restaurants they have checked in, which will consist of different columns: restaurant name, restaurant rating, food had (optional), date, occasion (breakfast, lunch, dinner). Users who interact with this profile can sort this by different categories (high to low rating; sort by the time of day, sort by cuisines)

**Comment by hongzipkim** [comment]
**Constructor** user
String id
String firstName
String lastName
String username
String password
String email 
Posts[] userPosts
String[] friends
HashMap flaggedRestaraunts
String[] friends
String[] followers
String[] following

**Comment by ArihantBapna** [comment]
Completed in user-profile-backend-to-frontend
